### ISSUE TITLE
Heels Plugin integration

### ISSUE THREAD

**Issue by VivyBehe** [PayneZA/OutfitManager#1]
Hi, I was wondering if it was possible to integrate the Outfit Manager with LeonBlade's Heels plugin. 

I have no idea how it would work so I don't even know if this can be done; but it would really make this plugin a 1000/10 for me personally if I had the ability to link heel/height offsets from Heels Plugin with Outfit Manager so that I could enable/disable offsets for the same vanilla item in different outfits.

i.e. I'm using Rebel Boots in 2 different outfit/collections under a different mod each that have different heel heights and I can switch between the 2 outfits without having to manually go to the Heels interface and enable/disable the specific entry. Or just in general being able to turn off heel height when I switch to a different collection so the offsets don't interfere with vanilla shoes when the mod is not in use. 

Again, I have no experience with making plugins so this could just be wishful thinking. Thanks!

**Comment by GunB** [comment]
I would love to add to this Palette as well. CHanging outfits and characters  without the color schemes is still a huge help but wished it was even more up there

**Comment by PayneZA** [comment]
To the original post, apologies on not responding sooner, I missed the original notification.

Heels and Customize don't work the same way when it comes to configuring, all this is doing is doing the penumbra and glamourer chat commands (basically you could achieve the same as this does with normal game macro's just lots of them).

I do get the outfits and scaling for sure but unfortunately not a feature that will come.
