### ISSUE TITLE
Remote management

### ISSUE THREAD

**Issue by AuroraLynnRN** [PayneZA/OutfitManager#11]
It appears that I should be able to give control of my outfits to another character that they can control via tells. I have made sure to set up outfits and that "Allow Chat Control" is checked. I have also put the character that I want to have control is set in the allow list. I have full control of outfits on my end with /omg commands. I cannot find any instructions on potential phrases the other character can say to have the control as well. So far we've tried the omg wear [outfit name] just without the slash. Is there something I'm missing in the ability to control or am I missing the correct phrase to do so?

**Comment by PayneZA** [comment]
Hi, if the other person has omg and goes "/omg other" they will have a opportunity to import outfits from clipboard (which you would get from on the standard view the Export all outfits to clipboard option). 

So step 1: Export all outfits to clipboard and give to friend
Step 2: friend copies the code and goes into the /omg other , click import outfits from clipboard
step 3: friend clicks you character name (it would be auto imported), chooses a outfit and does send wear outfit

It's really just a "/tell person@world wear:OutfitName"

**Comment by AuroraLynnRN** [comment]
This works perfectly. Thank you so much!
