### ISSUE TITLE
Feature Request: Associate customize+ scale with outfit

### ISSUE THREAD

**Issue by pictochatting** [PayneZA/OutfitManager#4]
https://github.com/XIV-Tools/CustomizePlus

It has a command interface - e.g. `/customize-apply <name> <scale name>`
I believe it also has an IPC interface!

Appreciate OutfitManager a lot - thank you for your work on it!

**Comment by PayneZA** [comment]
Hello

Customize support is something I have wanted to implement but when I first looked into it there was nothing I could do.

Thankyou for pointing this out, I'll put it high on my todo list as its a feature many have wanted (including myself).

**Comment by PayneZA** [comment]
Would working like this be fine

1 - There would need to be a default body scale in config, "DefaultBodyScale" as its name
2 - Outfit would have a field for scale name, when worn, scale applied.
3 - When equipping an outfit and no body scale exists or using the reset command, the default scaling is applied if one has been set in config.

I only ever just use 1 scale for everything with tiny adjustments but thats how I'd imagine multi-scaling working.
