### ISSUE TITLE
Feature Request: Execute arbitrary commands on outfit change

### ISSUE THREAD

**Issue by pictochatting** [PayneZA/OutfitManager#5]
More generally if there was a way to associate outfits with arbitrary set of commands, people could make their own integrations to whatever plugins exist. (e.g. Change c+ scale, change palette+, toggle game settings).

New Behavior:
`/omg wear outfit1 -> changes Collection, Glamourer Design, and executes any user-defined commands`

Some cons of this is that you could always do this with a normal macro e.g. 

```
/omg wear outfit1
/otherCommands
...
```

However I think a lot of people are searching for a centralized, all-in-one solution so having the flow just be `/omg wear outfit` and having OutfitManager do it's magic & run whatever commands you need for that specific outfit would be super clean.

**Comment by PayneZA** [comment]
I am trying to avoid using chat command as much as possible, its only supported if I cant directly talk to the plugin itself.

While custom commands is something that could be done you also then open up a whole new bag of potential problems, both for me and the user, say for example the custom command was to another plugin and that plugin changed then all of a sudden the outfits no longer applying properly for the person, with a lot of people not being technical a large amount of handholding starts to come into play.

I like outfit manager to always work for everything it's made for and custom commands introduces an unknown so I'd rather avoid that.
