### ISSUE TITLE
Feature Request: Folders or tag filtering

### ISSUE THREAD

**Issue by Iyadriel** [PayneZA/OutfitManager#6]
Appreciate your work on this plugin, makes having lots of outfits actually manageable.

I'd love to see folders in the outfit list. Currently I use prefixes in all my outfit names to more easily browse related outfits. This can be dresses, swimwear, combat attire, but also outfits per job.

Since there is already a tag system maybe tag filtering could work as well? I imagine this is something you've already thought of. Just adding my two cents for this.

**Comment by PayneZA** [comment]
It adds a bit of complexity with folders.
I personally name every outfit with a prefix then make use of the filter box, I don't plan on tag filtering to keep clutter down as well as the fact that it's really no better than using filtering, e.g. if you chose dresses tag and you then want to go to swimsuits you go to the swimsuits tag but then you have to also be adding tags when you make an outfit or you'd have a "general" one which most people would use. Easier to just partially type in filters.
