### ISSUE TITLE
Feature Request: Easier separation by character

### ISSUE THREAD

**Issue by Iyadriel** [PayneZA/OutfitManager#7]
When I log in on a different character I often find that collections will be applied from another character. This may be due to my settings, but I like the way my settings are for usage within the same character.

It would be good to have a way to completely separate the active collection by character. Extra nice would be to also separate the outfit list, though this could be achieved with folders/tag filtering (#6).

Thank you so much for this plugin!

**Comment by PayneZA** [comment]
Hi

This currently only exists for collections, for that part if you go into config (/omg config) there is "Penumbra collection type".

I will be making changes to the re-wear system once the new glamourer version comes out as a lot of it wont be needed anymore with glamourer remembering between zones your glamour, more like a "apply last outfit on login".

I can look into per-character "last outfit on login" then.

**Comment by Iyadriel** [comment]
Awesome! Thank you for this!
